name: Automated tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run Docker Compose
        run: docker compose up -d
      - name: Test
        run: docker run --network container:webapp-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000/
      - name: Run tests
        run: pytest

